Repository luabase/lua-dbt, pull requests merged in 2022-07, with the labels that each got.

#9 Specify `prod` profile target for CI pipeline runs
  lua_dbt.sh
Labels: enhancement

#7 Add Ethereum ABIs model
  models/ethereum/abis.sql
  models/ethereum/schema.yml
  models/ethereum/source.yml
Labels: enhancement

#14 Add remaining Avalanche model schema configs
  dbt_project.yml
  docs/blocks.md
  docs/logs.md
  docs/transactions.md
  models/avalanche/schema.yml
Labels: enhancement

#16 Add `avalanche` to SQL script
  updateLuaSchema.py
Labels: enhancement

#20 Add missing model description for Avalanche traces
  models/avalanche/schema.yml
Labels: bug

#24 Add model for Maple Pool events to analyses
  analyses/ethereum_maple_pool_events.sql
Labels: enhancement

#23 Add remaining Polygon models
  models/avalanche/schema.yml
  models/polygon/polygon_contracts.sql
  models/polygon/polygon_token_transfers.sql
  models/polygon/polygon_tokens.sql
  models/polygon/schema.yml
  models/polygon/source.yml
Labels: enhancement

#22 Migrate Ethereum sources
  models/ethereum/domains.sql
  models/ethereum/ethereum_abis.sql
  models/ethereum/ethereum_blocks.sql
  models/ethereum/ethereum_contracts.sql
  models/ethereum/ethereum_domains.sql
  models/ethereum/ethereum_events.sql
  models/ethereum/ethereum_logs.sql
  models/ethereum/ethereum_nft_events.sql
  models/ethereum/ethereum_tags.sql
  models/ethereum/ethereum_token_transfers.sql
  models/ethereum/ethereum_tokens.sql
  models/ethereum/ethereum_traces.sql
  models/ethereum/ethereum_transactions.sql
  models/ethereum/logs.sql
  models/ethereum/nft_events.sql
  models/ethereum/schema.yml
  models/ethereum/source.yml
  models/ethereum/tags.sql
  models/ethereum/transactions.sql
Labels: enhancement

#31 Fix build error for missing node
  analyses/ethereum_maple_pool_events.sql
Labels: bug

#33 Add `dbt deps` and `dbt seed` to build script
  lua_dbt.sh
Labels: enhancement

#37 Update Ethereum events source
  models/ethereum/ethereum_events.sql
  models/ethereum/ethereum_tokens.sql
  models/ethereum/source.yml
Labels: enhancement

#38 Prep for wider data quality initiatives
  cloudbuild.yaml
  dbt_project.yml
  macros/testing/regression_test__row_count.sql
  models/avalanche/schema.yml
  models/ethereum/source.yml
  models/polygon/schema.yml
  tests/.gitkeep
  tests/regression/bitcoin/row_count__bitcoin_blocks.sql
  tests/regression/bitcoin/row_count__bitcoin_transaction_inputs.sql
  tests/regression/bitcoin/row_count__bitcoin_transaction_outputs.sql
  tests/regression/bitcoin/row_count__bitcoin_transactions.sql
  tests/regression/ethereum/row_count__ethereum_blocks.sql
  tests/regression/ethereum/row_count__ethereum_domains.sql
  tests/regression/ethereum/row_count__ethereum_events.sql
  tests/regression/ethereum/row_count__ethereum_logs.sql
  tests/regression/ethereum/row_count__ethereum_nft_events.sql
  tests/regression/ethereum/row_count__ethereum_tags.sql
  tests/regression/ethereum/row_count__ethereum_transactions.sql
  tests/regression/polygon/row_count__polygon_blocks.sql
  tests/regression/polygon/row_count__polygon_logs.sql
  tests/regression/polygon/row_count__polygon_traces.sql
  tests/regression/polygon/row_count__polygon_transactions.sql
  tests/regression/prices/row_count__prices_btc_usd.sql
  tests/regression/prices/row_count__prices_eth_usd.sql
  tests/regression/prices/row_count__prices_sol_usd.sql
Labels: enhancement

#47 Ensure address is lowercase in Ethereum Domains model
  models/ethereum/ethereum_domains.sql
Labels: bug

#48 Remove nft events model
  models/ethereum/ethereum_nft_events.sql
  models/ethereum/schema.yml
Labels: bug

#49 Update column descriptions for Ethereum contracts
  models/ethereum/schema.yml
Labels: documentation

#50 add avax and matic
  models/prices/avax_usd.sql
  models/prices/matic_usd.sql
  models/prices/schema.yml
  models/prices/source.yml
Labels: enhancement

#51 Fix source
  models/prices/source.yml
Labels: bug

#52 Update ethereum transaction gas field descriptions
  models/ethereum/schema.yml
Labels: documentation

#53 Add missing column descriptions
  models/ethereum/schema.yml
Labels: documentation

#56 Specify that timestamps are in UTC
  models/avalanche/schema.yml
  models/bitcoin/schema.yml
  models/ethereum/schema.yml
  models/polygon/schema.yml
Labels: documentation

#57 Add updated link with class tag
  models/ethereum/schema.yml
Labels: documentation
